#!/bin/bash

delete_ep_and_port () {
    ep_name=$1
    neutron external-port-delete $ep_name
    neutron port-delete port_$ep_name
}

NET_NAME=mynet
SUBNET_NAME=mysubnet
ROUTER_NAME=router1
AP_NAME=myapoint
DO_ALL=$1

if [ -n "$DO_ALL" ]
then
    delete_ep_and_port myep
	# add your external ports here

	nova delete ${NET_NAME}_vm
	sleep 1
fi

neutron attachment-point-detach $AP_NAME
neutron attachment-point-delete $AP_NAME

neutron router-interface-delete $ROUTER_NAME $SUBNET_NAME
neutron subnet-delete $SUBNET_NAME
neutron net-delete $NET_NAME

